# fly.toml app configuration file generated for notion-md-translator on 2024-05-02T01:25:14+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "crypto-market-api"
primary_region = "waw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
